/* ============================================================
   Word + clue database (shared by the puzzle generators).
   Each entry maps an uppercase word to a short clue.
   Words are common, original content — nothing copied from
   published puzzle books.
   ============================================================ */

(function (global) {
  "use strict";

  var WORD_DATA = {

    animals: {
      "APE": "Large tailless primate",
      "BAT": "Mammal that flies at night",
      "BEE": "Stinging insect that makes honey",
      "CAT": "Feline pet that purrs",
      "COD": "North Atlantic food fish",
      "COW": "Farm animal that gives milk",
      "DOG": "Man's best friend",
      "EEL": "Long snakelike fish",
      "ELK": "Large deer with big antlers",
      "FOX": "Cunning wild dog with a bushy tail",
      "HEN": "Female chicken",
      "OWL": "Night bird that hoots",
      "PIG": "Farm animal that oinks",
      "RAT": "Rodent often found near humans",
      "RAM": "Male sheep",
      "YAK": "Long-haired ox of Tibet",
      "ANT": "Tiny insect that lives in colonies",
      "EMU": "Large flightless Australian bird",
      "GNU": "African antelope, the wildebeest",
      "KITE": "Bird of prey with a forked tail",
      "DEER": "Forest animal with antlers",
      "FROG": "Amphibian that croaks",
      "HARE": "Fast long-eared animal like a rabbit",
      "LAMB": "Young sheep",
      "MOLE": "Burrowing mammal with poor eyesight",
      "NEWT": "Small amphibian with a tail",
      "OTTER": "Playful river mammal that eats fish",
      "PANDA": "Black-and-white bear from China",
      "SEAL": "Flippered marine mammal",
      "TOAD": "Warty amphibian",
      "WOLF": "Wild dog that howls",
      "ZEBRA": "Striped African horse",
      "BISON": "Large shaggy American ox",
      "CAMEL": "Desert animal with humps",
      "CRANE": "Long-legged wading bird",
      "EAGLE": "Large bird of prey",
      "GECKO": "Small lizard with sticky toes",
      "GOOSE": "Water bird that honks",
      "KOALA": "Australian bear-like marsupial",
      "LEMUR": "Large-eyed primate of Madagascar",
      "LLAMA": "South American woolly animal",
      "MOOSE": "Huge deer with broad antlers",
      "MOUSE": "Small rodent, a favorite of cats",
      "RAVEN": "Large black crow-like bird",
      "ROBIN": "Small bird with a red breast",
      "SHARK": "Fearsome ocean fish with fins",
      "SNAKE": "Legless reptile that slithers",
      "SWAN": "Graceful white water bird",
      "TIGER": "Striped big cat",
      "VIPER": "Venomous snake",
      "WHALE": "Huge ocean mammal",
      "BADGER": "Black-and-white burrowing mammal",
      "BEAVER": "Rodent that builds dams",
      "COUGAR": "Large wild cat, the puma",
      "DONKEY": "Animal that brays",
      "FALCON": "Fast-flying bird of prey",
      "FERRET": "Playful domesticated weasel",
      "FINCH": "Small seed-eating songbird",
      "GAZELLE": "Swift graceful antelope",
      "GOPHER": "Burrowing North American rodent",
      "HERON": "Long-legged wading bird",
      "JACKAL": "Wild dog of Africa and Asia",
      "JAGUAR": "Spotted big cat of the Americas",
      "JELLYFISH": "Translucent ocean animal with tentacles",
      "KANGAROO": "Australian animal that hops",
      "LOBSTER": "Clawed shellfish that turns red when cooked",
      "MARMOT": "Large burrowing ground squirrel",
      "MONKEY": "Tree-dwelling primate",
      "OSTRICH": "Largest bird, cannot fly",
      "PENGUIN": "Flightless Antarctic bird",
      "RABBIT": "Long-eared burrowing animal",
      "RACCOON": "Mask-faced night animal",
      "SALMON": "Fish that swims upstream to spawn",
      "SQUID": "Ocean animal with ten tentacles",
      "TURKEY": "Large bird eaten at Thanksgiving",
      "TURTLE": "Slow reptile with a shell",
      "WALRUS": "Sea mammal with long tusks",
      "WEASEL": "Small slender carnivorous mammal",
      "BUFFALO": "Large horned ox",
      "DOLPHIN": "Playful intelligent sea mammal",
      "FLAMINGO": "Pink wading bird",
      "GIRAFFE": "Tallest animal, with a long neck",
      "GORILLA": "Largest ape",
      "HEDGEHOG": "Spiny mammal that rolls into a ball",
      "LEOPARD": "Spotted big cat",
      "OCTOPUS": "Eight-armed ocean animal",
      "PARROT": "Colorful bird that can talk",
      "PELICAN": "Bird with a large throat pouch",
      "PIGEON": "Common city bird that coos",
      "PLATYPUS": "Egg-laying duck-billed mammal",
      "PORCUPINE": "Rodent covered in quills",
      "SQUIRREL": "Bushy-tailed nut eater",
      "STARFISH": "Five-armed sea animal",
      "CHEETAH": "Fastest land animal",
      "ALLIGATOR": "Large reptile of southern US swamps",
      "BUTTERFLY": "Colorful winged insect",
      "CROCODILE": "Large tropical reptile",
      "ELEPHANT": "Largest land animal, with a trunk",
      "HUMMINGBIRD": "Tiny bird that hovers and drinks nectar",
      "WOODPECKER": "Bird that taps trees for insects"
    },

    foods: {
      "BUN": "Round bread roll for a burger",
      "EGG": "Breakfast food laid by a hen",
      "FIG": "Sweet fruit with edible seeds",
      "HAM": "Smoked leg of pork",
      "JAM": "Sweet fruit spread",
      "NUT": "Hard-shelled snack, e.g. almond",
      "OAT": "Grain used for porridge",
      "PEA": "Small round green vegetable",
      "PIE": "Baked dish with a pastry crust",
      "RYE": "Grain used for dark bread",
      "YAM": "Sweet starchy root vegetable",
      "BACON": "Smoked breakfast meat",
      "BAGEL": "Ring-shaped boiled bread",
      "BEANS": "Legumes in a can or a pod",
      "BREAD": "Staple baked from flour",
      "CAKE": "Sweet baked dessert with frosting",
      "CHILI": "Spicy stew with beans",
      "CREPE": "Thin French pancake",
      "CURRY": "Spiced Indian dish with sauce",
      "DATES": "Sweet brown fruit of palm trees",
      "GRAPE": "Fruit used to make wine",
      "HONEY": "Sweet syrup made by bees",
      "MELON": "Large juicy fruit such as cantaloupe",
      "MANGO": "Tropical fruit with a big pit",
      "OLIVE": "Small oily fruit, green or black",
      "ONION": "Layered vegetable that makes you cry",
      "PASTA": "Italian staple made from wheat",
      "PEACH": "Fuzzy-skinned summer fruit",
      "PIZZA": "Italian flatbread with toppings",
      "PLUM": "Purple stone fruit",
      "PRUNE": "Dried plum",
      "QUICHE": "Savory egg pie",
      "SALAD": "Dish of mixed vegetables",
      "SALSA": "Spicy tomato dip",
      "SUSHI": "Japanese dish of vinegared rice",
      "TOAST": "Sliced bread that has been browned",
      "TORTE": "Rich layered cake",
      "APPLE": "Common fruit that keeps the doctor away",
      "AVOCADO": "Green fruit used for guacamole",
      "BANANA": "Long yellow curved fruit",
      "BROCCOLI": "Green vegetable that looks like a tree",
      "BURGER": "Beef patty in a bun",
      "BUTTER": "Spread churned from cream",
      "CARROT": "Orange root vegetable rabbits love",
      "CASHEW": "Curved kidney-shaped nut",
      "CELERY": "Crunchy green stalk vegetable",
      "CHERRY": "Small red fruit with a pit",
      "CHEESE": "Dairy food made from curdled milk",
      "CHICKEN": "Poultry that lays eggs",
      "COOKIE": "Sweet baked treat with chips",
      "CRACKER": "Thin crisp savory biscuit",
      "DONUT": "Fried ring-shaped pastry",
      "GARLIC": "Pungent bulb used in cooking",
      "GINGER": "Spicy root used in Asian cooking",
      "KIWI": "Fuzzy brown fruit with green flesh",
      "LEMON": "Sour yellow citrus fruit",
      "LETTUCE": "Leafy green used in salads",
      "LIME": "Green citrus fruit",
      "MUFFIN": "Small baked breakfast cake",
      "NOODLE": "Long thin strand of pasta",
      "ORANGE": "Round citrus fruit",
      "PAPAYA": "Tropical orange-fleshed fruit",
      "PEPPER": "Spicy pod or seasoning",
      "PICKLE": "Cucumber preserved in brine",
      "POTATO": "Starchy tuber, mashed or fried",
      "PRETZEL": "Twisted salted snack",
      "PUMPKIN": "Orange gourd carved at Halloween",
      "RAISIN": "Dried grape",
      "SPINACH": "Leafy green, Popeye's favorite",
      "TOMATO": "Red fruit used in sauces",
      "WALNUT": "Wrinkled brown nut",
      "YOGURT": "Thick fermented milk product",
      "ALMOND": "Nut used to make marzipan",
      "CABBAGE": "Round leafy vegetable",
      "COCONUT": "Hairy tropical fruit with milk",
      "CUCUMBER": "Long green salad vegetable",
      "LASAGNA": "Baked Italian layered pasta dish",
      "PANCAKE": "Flapjack served with syrup",
      "SAUSAGE": "Seasoned meat in a casing",
      "SANDWICH": "Filling between two slices of bread",
      "SPAGHETTI": "Long thin pasta with sauce",
      "STRAWBERRY": "Red fruit with seeds on the outside",
      "WAFFLE": "Grid-patterned breakfast pastry",
      "BLUEBERRY": "Small blue berry",
      "RASPBERRY": "Red berry with a hollow core",
      "PINEAPPLE": "Tropical fruit with spiky skin",
      "POMEGRANATE": "Red fruit full of seeds",
      "WATERMELON": "Huge juicy fruit with a green rind",
      "CAULIFLOWER": "White vegetable related to broccoli",
      "EGGPLANT": "Purple vegetable, also called aubergine",
      "ARTICHOKE": "Thistle-like vegetable with edible leaves",
      "CANTALOUPE": "Orange-fleshed melon",
      "MUSHROOM": "Edible fungus with a cap",
      "HAMBURGER": "Ground beef patty in a bun",
      "CHEESEBURGER": "Hamburger topped with dairy"
    },

    sports: {
      "DARTS": "Game of throwing small missiles at a board",
      "GOLF": "Sport played with clubs and a small ball",
      "JUDO": "Japanese martial art of throws",
      "POLO": "Horseback sport played with mallets",
      "RUGBY": "Contact sport with an oval ball",
      "SURFING": "Riding ocean waves on a board",
      "TENNIS": "Racket sport with a yellow ball",
      "YOGA": "Discipline of poses and breathing",
      "ARCHERY": "Sport of shooting arrows",
      "BOXING": "Fighting sport with gloved fists",
      "BOWLING": "Rolling a ball to knock down pins",
      "CRICKET": "Bat-and-ball sport with wickets",
      "CURLING": "Sport of sliding stones on ice",
      "CYCLING": "Riding bicycles as a sport",
      "DIVING": "Jumping into water headfirst",
      "FENCING": "Sport of sword fighting",
      "HOCKEY": "Ice sport played with sticks and a puck",
      "JOGGING": "Slow steady running",
      "KARATE": "Japanese martial art with strikes",
      "ROWING": "Propelling a boat with oars",
      "SKIING": "Sliding downhill on skis",
      "SOCCER": "The world's most popular sport, played with a round ball",
      "SPRINT": "Short fast race",
      "SWIMMING": "Moving through water as a sport",
      "BASEBALL": "American bat-and-ball sport with bases",
      "BASKETBALL": "Hoops sport played with a bouncing ball",
      "BADMINTON": "Racket sport with a shuttlecock",
      "HANDBALL": "Team sport throwing a ball into a goal",
      "MARATHON": "Race of about 26 miles",
      "SKATING": "Gliding on ice or wheels",
      "SNOWBOARDING": "Sliding down snow on one board",
      "VOLLEYBALL": "Net sport played with an overhand hit",
      "WEIGHTLIFTING": "Sport of lifting heavy barbells",
      "GYMNASTICS": "Sport of flips, bars and balance",
      "BOBSLED": "Racing down an ice track in a sled",
      "CANOEING": "Paddling a narrow open boat",
      "KAYAKING": "Paddling a closed-top boat",
      "PARAGLIDING": "Flying with a canopy and harness",
      "SAILING": "Moving a boat using wind power",
      "SNORKELING": "Swimming with a breathing tube",
      "TAEKWONDO": "Korean martial art with kicks",
      "TRIATHLON": "Race combining swim, bike and run",
      "WRESTLING": "Grappling sport to pin an opponent",
      "SKATEBOARDING": "Riding a board on wheels",
      "PARKOUR": "Moving through urban obstacles by running and vaulting",
      "JAVELIN": "Track event throwing a spear",
      "HURDLES": "Track race over barriers",
      "DISCUS": "Track and field event throwing a heavy plate",
      "BIKE": "Two-wheeled vehicle ridden for sport",
      "CLIMB": "Scale a rock face (sport)",
      "CURL": "Lift a heavy barbell, in gym slang",
      "DIVE": "Plunge headfirst into water",
      "GYM": "Place for exercise",
      "HIKE": "Long walk in nature",
      "JOG": "Run at a gentle pace",
      "LUGE": "Racing on a sled feet-first",
      "PUTT": "Gentle golf stroke on the green",
      "RACE": "Competition of speed",
      "RALLY": "Long-distance motorsport event",
      "RODEO": "Cowboy sport with bucking broncos",
      "ROW": "Propel a boat with oars",
      "RUN": "Move fast on foot",
      "SHOOT": "Fire a gun or arrow in competition",
      "SKI": "Slide on snow on long boards",
      "SKATE": "Glide on ice or wheels",
      "SQUASH": "Racket sport played in an enclosed court",
      "SUMO": "Japanese wrestling of large men",
      "SURF": "Ride ocean waves",
      "SWIM": "Move through water",
      "ZUMBA": "Dance fitness class",
      "FUTSAL": "Indoor soccer played with a small ball"
    },

    countries: {
      "CHAD": "African country with capital N'Djamena",
      "FIJI": "Pacific island nation with capital Suva",
      "GHANA": "West African country with capital Accra",
      "IRAN": "Middle Eastern country with capital Tehran",
      "IRAQ": "Middle Eastern country with capital Baghdad",
      "LAOS": "Southeast Asian country with capital Vientiane",
      "MALI": "West African country with capital Bamako",
      "NEPAL": "Himalayan country with capital Kathmandu",
      "PERU": "South American country with capital Lima",
      "QATAR": "Gulf country with capital Doha",
      "TOGO": "West African country on the Gulf of Guinea",
      "CHILE": "Long South American country with capital Santiago",
      "CHINA": "Most populous country, capital Beijing",
      "EGYPT": "North African country with capital Cairo",
      "FRANCE": "European country with capital Paris",
      "GABON": "Central African country with capital Libreville",
      "GREECE": "European country with capital Athens",
      "HAITI": "Caribbean country sharing an island with the Dominican Republic",
      "INDIA": "South Asian country with capital New Delhi",
      "ITALY": "European country with capital Rome",
      "JAPAN": "East Asian island country with capital Tokyo",
      "KENYA": "East African country with capital Nairobi",
      "KOREA": "East Asian peninsula divided into two countries",
      "LIBYA": "North African country with capital Tripoli",
      "MALTA": "Mediterranean island nation with capital Valletta",
      "NIGER": "Landlocked West African country with capital Niamey",
      "PALAU": "Pacific island nation west of the Philippines",
      "SAMOA": "Pacific island nation with capital Apia",
      "SPAIN": "European country with capital Madrid",
      "SUDAN": "North African country with capital Khartoum",
      "SYRIA": "Middle Eastern country with capital Damascus",
      "TONGA": "South Pacific island kingdom",
      "YEMEN": "Arabian country with capital Sanaa",
      "BELGIUM": "European country with capital Brussels",
      "BHUTAN": "Himalayan country with capital Thimphu",
      "BRAZIL": "Largest South American country, capital Brasilia",
      "CANADA": "North American country with capital Ottawa",
      "CROATIA": "European country with capital Zagreb",
      "CUBA": "Caribbean island country with capital Havana",
      "CYPRUS": "Mediterranean island nation with capital Nicosia",
      "DENMARK": "Scandinavian country with capital Copenhagen",
      "FINLAND": "Nordic country with capital Helsinki",
      "GERMANY": "European country with capital Berlin",
      "HUNGARY": "Central European country with capital Budapest",
      "ICELAND": "North Atlantic island country with capital Reykjavik",
      "IRELAND": "Island country west of Britain, capital Dublin",
      "ISRAEL": "Middle Eastern country with capital Jerusalem",
      "JAMAICA": "Caribbean island nation with capital Kingston",
      "JORDAN": "Middle Eastern country with capital Amman",
      "MEXICO": "North American country with capital Mexico City",
      "MONACO": "Tiny European principality on the Riviera",
      "NORWAY": "Scandinavian country with capital Oslo",
      "PANAMA": "Central American country with a famous canal",
      "POLAND": "European country with capital Warsaw",
      "ROMANIA": "European country with capital Bucharest",
      "RWANDA": "East African country with capital Kigali",
      "SERBIA": "Balkan country with capital Belgrade",
      "SWEDEN": "Scandinavian country with capital Stockholm",
      "THAILAND": "Southeast Asian country with capital Bangkok",
      "TUNISIA": "North African country with capital Tunis",
      "TURKEY": "Country straddling Europe and Asia, capital Ankara",
      "UKRAINE": "European country with capital Kyiv",
      "VIETNAM": "Southeast Asian country with capital Hanoi",
      "ZAMBIA": "Southern African country with capital Lusaka",
      "AUSTRALIA": "Country-continent with capital Canberra",
      "ARGENTINA": "South American country with capital Buenos Aires",
      "AUSTRIA": "European country with capital Vienna",
      "BOLIVIA": "Landlocked South American country named after Simon Bolivar",
      "BULGARIA": "European country with capital Sofia",
      "COLOMBIA": "South American country with capital Bogota",
      "ECUADOR": "South American country on the Equator, capital Quito",
      "ETHIOPIA": "East African country with capital Addis Ababa",
      "HONDURAS": "Central American country with capital Tegucigalpa",
      "INDONESIA": "Southeast Asian archipelago with capital Jakarta",
      "MALAYSIA": "Southeast Asian country with capital Kuala Lumpur",
      "MONGOLIA": "Asian country with capital Ulaanbaatar",
      "MOROCCO": "North African country with capital Rabat",
      "MOZAMBIQUE": "Southeast African country with capital Maputo",
      "NAMIBIA": "Southwest African country with capital Windhoek",
      "NICARAGUA": "Central American country with capital Managua",
      "NIGERIA": "Most populous African country, capital Abuja",
      "PAKISTAN": "South Asian country with capital Islamabad",
      "PARAGUAY": "South American country with capital Asuncion",
      "PORTUGAL": "European country with capital Lisbon",
      "SENEGAL": "West African country with capital Dakar",
      "SINGAPORE": "City-state in Southeast Asia",
      "SLOVAKIA": "Central European country with capital Bratislava",
      "SLOVENIA": "European country with capital Ljubljana",
      "SOMALIA": "Horn of Africa country with capital Mogadishu",
      "TANZANIA": "East African country with capital Dodoma",
      "URUGUAY": "South American country with capital Montevideo",
      "VENEZUELA": "South American country with capital Caracas",
      "ZIMBABWE": "Southern African country with capital Harare",
      "SWITZERLAND": "Alpine European country with capital Bern",
      "PHILIPPINES": "Southeast Asian island nation with capital Manila"
    },

    jobs: {
      "COOK": "One who prepares meals",
      "CHEF": "Head cook in a restaurant",
      "NURSE": "Medical worker who cares for patients",
      "PILOT": "One who flies an aircraft",
      "JUDGE": "One who presides over a court",
      "MASON": "Worker who builds with stone or brick",
      "BAKER": "One who makes bread and pastries",
      "TAILOR": "One who makes and fits suits",
      "BARBER": "One who cuts men's hair",
      "ACTOR": "One who performs in plays and films",
      "GUARD": "One who protects a building or person",
      "CLERK": "Office worker who keeps records",
      "DRIVER": "One who operates a vehicle",
      "FARMER": "One who grows crops and raises livestock",
      "ARTIST": "One who paints or draws",
      "WRITER": "One who authors books or articles",
      "SINGER": "One who performs songs",
      "DANCER": "One who moves to music",
      "DOCTOR": "Physician who treats patients",
      "LAWYER": "One who practices law",
      "PLUMBER": "One who fixes pipes",
      "PAINTER": "One who applies paint for a living",
      "TEACHER": "One who instructs students",
      "DENTIST": "Doctor who cares for teeth",
      "SURGEON": "Doctor who performs operations",
      "CHEMIST": "Scientist who works with chemicals",
      "JANITOR": "One who cleans and maintains a building",
      "WAITER": "One who serves food in a restaurant",
      "CASHIER": "One who handles money at a checkout",
      "BARISTA": "One who makes coffee drinks",
      "LIBRARIAN": "One who manages a library",
      "ENGINEER": "One who designs machines or structures",
      "MECHANIC": "One who repairs cars",
      "ARCHITECT": "One who designs buildings",
      "SCIENTIST": "One who conducts experiments",
      "MUSICIAN": "One who plays an instrument",
      "PHOTOGRAPHER": "One who takes pictures",
      "FIREFIGHTER": "One who puts out fires",
      "HAIRDRESSER": "One who styles hair",
      "ACCOUNTANT": "One who prepares financial records",
      "JOURNALIST": "One who reports the news",
      "DESIGNER": "One who creates visual concepts",
      "PROGRAMMER": "One who writes computer code",
      "ASTRONAUT": "One who travels into space",
      "VETERINARIAN": "Animal doctor",
      "PHARMACIST": "One who dispenses medicine",
      "CARPENTER": "One who builds with wood",
      "BLACKSMITH": "One who forges iron",
      "FISHERMAN": "One who catches fish for a living",
      "ELECTRICIAN": "One who installs wiring",
      "PSYCHOLOGIST": "One who studies the mind",
      "PARAMEDIC": "Emergency medical responder",
      "TRANSLATOR": "One who converts between languages",
      "RECEPTIONIST": "One who greets visitors at a desk",
      "SUPERVISOR": "One who oversees workers",
      "MACHINIST": "One who operates metalworking machines",
      "WELDER": "One who joins metal with heat",
      "GLASSBLOWER": "One who shapes glass with breath",
      "LOCKSMITH": "One who makes and repairs locks",
      "UPHOLSTERER": "One who fits furniture with fabric",
      "BOOKKEEPER": "One who records financial transactions",
      "PALEONTOLOGIST": "One who studies fossils",
      "VET": "Animal doctor, for short",
      "COP": "Police officer, informally",
      "NUN": "Woman devoted to religious life",
      "MAID": "One who cleans houses",
      "PAGE": "Young attendant in a hotel or legislature",
      "DEAN": "Head of a university faculty",
      "POET": "One who writes verse",
      "MAYOR": "Elected head of a city",
      "COACH": "One who trains athletes",
      "USHER": "One who seats guests in a theater",
      "COURIER": "One who delivers packages",
      "BUTLER": "Chief male servant of a household",
      "PORTER": "One who carries luggage",
      "SCRIBE": "One who copies documents by hand",
      "SURFER": "One who rides ocean waves",
      "TRAINER": "One who prepares athletes",
      "WEAVER": "One who makes cloth on a loom",
      "RANGER": "Park warden who protects wildlife"
    },

    nature: {
      "BAY": "Body of water partly enclosed by land",
      "CAVE": "Natural underground hollow",
      "CLAY": "Fine earth used in pottery",
      "DEW": "Morning moisture on grass",
      "DUNE": "Hill of sand",
      "FOG": "Thick low cloud",
      "HILL": "Raised land, smaller than a mountain",
      "ICE": "Frozen water",
      "LAKE": "Large body of inland water",
      "MOSS": "Soft green plant on rocks",
      "OAK": "Tree that bears acorns",
      "PINE": "Evergreen tree with cones",
      "RAIN": "Water falling from clouds",
      "ROCK": "Hard natural stone",
      "SEA": "Large saltwater body",
      "SKY": "Space above the earth",
      "SNOW": "Frozen precipitation that falls as flakes",
      "SUN": "Star at the center of our solar system",
      "WIND": "Moving air",
      "BARK": "Tough outer covering of a tree",
      "FERN": "Leafy plant without flowers",
      "MOON": "Earth's natural satellite",
      "REED": "Tall grass growing in wetlands",
      "STAR": "Distant glowing body in the night sky",
      "TIDE": "Daily rise and fall of the sea",
      "WAVE": "Moving ridge of water",
      "ALPINE": "Relating to high mountains",
      "BEACH": "Sandy shore by the sea",
      "BIRCH": "White-barked tree",
      "BROOK": "Small stream",
      "CACTUS": "Spiny desert plant",
      "CANYON": "Deep gorge carved by a river",
      "CEDAR": "Fragrant evergreen tree",
      "CLIFF": "Steep rock face",
      "CLOUD": "Fluffy water vapor in the sky",
      "COAST": "Land along the sea",
      "DESERT": "Dry region with very little rain",
      "ELM": "Shade tree with arching branches",
      "FJORD": "Narrow sea inlet between cliffs",
      "FOREST": "Large area covered in trees",
      "GLACIER": "Slow-moving river of ice",
      "GRASSY": "Covered in short green plants",
      "ISLAND": "Land surrounded by water",
      "JUNGLE": "Dense tropical forest",
      "MAPLE": "Tree whose leaves turn red in autumn",
      "MEADOW": "Field of grass and wildflowers",
      "MOUNTAIN": "Very high raised area of land",
      "OCEAN": "Vast saltwater body",
      "ORCHID": "Showy tropical flower",
      "PRAIRIE": "Large flat grassland",
      "RIVER": "Large natural stream of water",
      "SHRUB": "Small woody plant",
      "STREAM": "Small flowing body of water",
      "SWAMP": "Wet, spongy land",
      "VALLEY": "Low land between hills",
      "VOLCANO": "Mountain that erupts lava",
      "WATERFALL": "Water falling over a cliff",
      "WILLOW": "Tree with drooping branches",
      "BAMBOO": "Fast-growing plant with hollow stems",
      "BOULDER": "Large rounded rock",
      "DAISY": "White-petaled flower with a yellow center",
      "DRIZZLE": "Light rain",
      "ECLIPSE": "When one celestial body blocks another",
      "GALAXY": "Huge system of stars",
      "GEYSER": "Hot spring that erupts water",
      "HORIZON": "Line where earth meets sky",
      "HURRICANE": "Powerful tropical storm",
      "LIGHTNING": "Bright electric flash in a storm",
      "MARSH": "Low wetland with grasses",
      "NEBULA": "Cloud of gas and dust in space",
      "PEBBLE": "Small smooth stone",
      "RAINBOW": "Arc of colors after rain",
      "SANDSTORM": "Windstorm carrying desert sand",
      "SEASHORE": "Land bordering the sea",
      "THUNDER": "Rumbling sound after lightning",
      "TORNADO": "Violent funnel-shaped storm",
      "TUNDRA": "Cold treeless Arctic plain",
      "TWILIGHT": "Soft light at dusk",
      "CROCUS": "Early-spring flowering plant",
      "DAFFODIL": "Yellow trumpet-shaped spring flower",
      "BLIZZARD": "Severe snowstorm",
      "EARTHQUAKE": "Shaking of the earth's crust",
      "AVALANCHE": "Rushing mass of snow down a mountain",
      "SUNFLOWER": "Tall flower that turns toward the sun",
      "EVERGREEN": "Tree that stays green all year",
      "WILDFLOWER": "Flower growing without cultivation",
      "CONSTELLATION": "Group of stars forming a pattern",
      "MOONLIGHT": "Light from the moon",
      "SNOWFLAKE": "Single crystal of snow",
      "HAILSTORM": "Storm of icy pellets",
      "MANGROVE": "Tropical coastal tree with exposed roots",
      "SAVANNA": "Tropical grassland with scattered trees",
      "WOODLAND": "Area covered with trees"
    }
  };

  var CATEGORY_LABELS = {
    animals: "Animals",
    foods: "Food & Drink",
    sports: "Sports",
    countries: "Countries",
    jobs: "Jobs",
    nature: "Nature"
  };

  global.WORD_DATA = WORD_DATA;
  global.CATEGORY_LABELS = CATEGORY_LABELS;
})(typeof window !== "undefined" ? window : globalThis);
